export const CHECK_BOOKING_REQUEST = 'CHECK_BOOKING_REQUEST';
export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS';
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET';
export const CHECK_BOOKING_FAILURE = 'CHECK_BOOKING_FAILURE';



export const CLEAR_ERROR = 'CLEAR_ERROR';


