export const CHECK_BOOKING_REQUEST = 'CHECK_BOOKING_REQUEST';
export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS';
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET';
export const CHECK_BOOKING_FAILURE = 'CHECK_BOOKING_FAILURE';

export const BOOKED_DATES_SUCCESS = 'BOOKED_DATES_SUCCESS';
export const BOOKED_DATES_FAILURE = 'BOOKED_DATES_FAILURE';

export const MY_BOOKING_SUCCESS = 'MY_BOOKING_SUCCESS';
export const MY_BOOKING_FAILURE = 'MY_BOOKING_FAILURE';

export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAILURE = 'BOOKING_DETAILS_FAILURE';

export const ADMIN_BOOKING_REQUEST = 'ADMIN_BOOKING_REQUEST';
export const ADMIN_BOOKING_SUCCESS = 'ADMIN_BOOKING_SUCCESS';
export const ADMIN_BOOKING_FAILURE = 'ADMIN_BOOKING_FAILURE';



export const CLEAR_ERROR = 'CLEAR_ERROR';


