export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAIL = 'ALL_ROOMS_FAIL';

export const ROOM_DETAIL_SUCCESS = 'ROOM_DETAIL_SUCCESS';
export const ROOM_DETAIL_FAIL = 'ROOM_DETAIL_FAIL';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_FAILURE = 'NEW_REVIEW_FAILURE';



export const CLEAR_ERROR = 'CLEAR_ERROR';